/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef VITTOR_DTU_SET_CPP_PRIVATE_H
#define VITTOR_DTU_SET_CPP_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.0.1.0"
#define VER_MAJOR	1
#define VER_MINOR	0
#define VER_RELEASE	1
#define VER_BUILD	0
#define COMPANY_NAME	"Vittor"
#define FILE_VERSION	"1.0.1.0"
#define FILE_DESCRIPTION	"微拓物联网数据传送单元配置程序"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"VittorDtuConfig"
#define PRODUCT_VERSION	"1.0.1.0"

#endif /*VITTOR_DTU_SET_CPP_PRIVATE_H*/
